"""
inference.py — Inference for CircadianTCN (Simulation Edition)
=====================================================================
Returns:
  - sleep_duration_hrs
  - insomnia_probability + risk_level
  - recovery_days (ML-predicted, not hardcoded math)
  - insomnia_risk_trajectory (7 days)
  - adaptation_strategy (ML-selected from 5 classes)
  - context_notes (jet lag / night shift personalisation)
  - clinical_disclaimer
"""

import os
import json
import numpy as np
import pandas as pd
import torch

from tcn_model import CircadianTCN
from preprocess import (
    engineer_features, create_windows,
    ENGINEERED_FEATURES, NUM_FEATURES, SEQ_LEN,
    INSOMNIA_ISI_THRESHOLD, STRATEGY_LABELS,
)

CLINICAL_DISCLAIMER = (
    "⚠️ SCREENING TOOL ONLY. This output is generated by a machine learning model "
    "trained on synthetic data. It is NOT a medical diagnosis. Always consult a "
    "qualified sleep physician, chronobiologist, or healthcare professional before "
    "making clinical decisions."
)

_model_cache = None


def load_model(model_path: str = "tcn_model.pth", device: str = "cpu"):
    global _model_cache
    if _model_cache is not None:
        return _model_cache

    if not os.path.exists(model_path):
        raise FileNotFoundError(
            f"Model not found at '{model_path}'. Run train_tcn_model.py first."
        )

    ckpt  = torch.load(model_path, map_location=device)
    cfg   = ckpt.get("config", {})
    model = CircadianTCN(
        num_features   = cfg.get("num_features",  NUM_FEATURES),
        seq_len        = cfg.get("seq_len",        SEQ_LEN),
        channels       = cfg.get("channels",       [64, 128, 128, 64]),
        kernel_size    = cfg.get("kernel_size",    3),
        dropout        = 0.0,
    )
    model.load_state_dict(ckpt["model_state"])
    model.eval()
    _model_cache = model
    return model


# ── Questionnaire converter v3 ───────────────────────────────────────────────

def questionnaire_to_raw(answers: dict) -> dict:
    """
    answers must include all original 12 fields plus:
      event_type        (int: 0=none, 1=jet_lag, 2=night_shift)
      tz_shift_hrs      (float: –12 to +12, 0 if not jet lag)
      shift_week        (int: 0 if not night shift)
      days_since_event  (int: days since event started)
      chronotype_score  (float: 0=extreme evening, 1=extreme morning)
    """
    required = [
        "sleep_duration_hrs", "sleep_efficiency", "heart_rate_resting",
        "rmssd", "sdnn", "steps", "light_exposure_lux", "bedtime_hour",
        "isi_score", "phq_score", "gad_score", "meq_score",
        "event_type", "tz_shift_hrs", "shift_week",
        "days_since_event", "chronotype_score",
    ]
    missing = [k for k in required if k not in answers]
    if missing:
        raise ValueError(f"Missing fields: {missing}")

    # Placeholder labels (not used at inference, but engineer_features needs them)
    out = {k: answers[k] for k in required}
    out["label_recovery_days"] = 0.0
    out["label_strategy"]      = 0
    out["label_insomnia_risk"] = 0.0
    return out


# ── Interpolate 1–7 days input ───────────────────────────────────────────────

def _pad_to_7(days: list) -> list:
    """Linearly interpolate if fewer than 7 days provided (min 1)."""
    if len(days) == SEQ_LEN:
        return days
    if len(days) > SEQ_LEN:
        return days[:SEQ_LEN]
    # Interpolate
    result = []
    n = SEQ_LEN
    src = days
    for i in range(n):
        t = i / (n - 1) * (len(src) - 1)
        lo = int(t)
        hi = min(lo + 1, len(src) - 1)
        frac = t - lo
        interp = {}
        for k in src[0]:
            v_lo = src[lo][k]
            v_hi = src[hi][k]
            if isinstance(v_lo, (int, float)):
                interp[k] = v_lo + frac * (v_hi - v_lo)
            else:
                interp[k] = v_lo
        result.append(interp)
    return result


# ── Main predict function ────────────────────────────────────────────────────

@torch.no_grad()
def predict_from_questionnaire(days: list, age: int = 35, gender: str = "unspecified",
                       model=None) -> dict:
    """
    days: list of 1–7 dicts with v3 fields (including event_type, tz_shift_hrs, etc.)
    Returns full structured result with ML-predicted simulation outputs.
    """
    days = _pad_to_7(days)
    if model is None:
        model = load_model()

    # Build raw df
    rows = []
    for i, d in enumerate(days):
        r = questionnaire_to_raw(d)
        r["subject_id"] = "new_user"
        r["date"]       = pd.Timestamp("2024-01-01") + pd.Timedelta(days=i)
        r["age"]        = age
        r["gender"]     = gender
        rows.append(r)

    raw_df = pd.DataFrame(rows)
    eng    = engineer_features(raw_df)
    X      = eng[ENGINEERED_FEATURES].values.astype(np.float32)   # (7, 19)

    # Forward pass
    t = torch.tensor(X, dtype=torch.float32).unsqueeze(0)            # (1, 7, 19)
    dur_p, ins_p, rec_p, traj_p, strat_p = model(t)

    dur_hrs  = float(dur_p[0])
    ins_prob = float(ins_p[0])
    rec_days = float(rec_p[0])
    traj     = traj_p[0].tolist()
    strat_id = int(strat_p[0].argmax())
    strat    = STRATEGY_LABELS[strat_id]

    # Risk stratification
    if ins_prob >= 0.75:
        risk_level, risk_color = "Severe",   "#ff2d55"
    elif ins_prob >= 0.50:
        risk_level, risk_color = "Moderate", "#ff9f0a"
    elif ins_prob >= 0.25:
        risk_level, risk_color = "Mild",     "#ffd60a"
    else:
        risk_level, risk_color = "Low",      "#30d158"

    # Duration label
    if dur_hrs < 5:        dur_label = "Severely Short"
    elif dur_hrs < 6:      dur_label = "Short"
    elif dur_hrs < 7:      dur_label = "Below Recommended"
    elif dur_hrs <= 9:     dur_label = "Optimal"
    else:                  dur_label = "Long"

    # Event context
    last_day    = days[-1]
    event_type  = int(last_day.get("event_type", 0))
    tz_shift    = float(last_day.get("tz_shift_hrs", 0))
    shift_week  = int(last_day.get("shift_week", 0))

    context_notes = _build_context_notes(event_type, tz_shift, shift_week,
                                          ins_prob, rec_days, strat_id, age)

    # Insights
    insights = _build_insights(dur_hrs, ins_prob, rec_days, traj,
                                event_type, tz_shift, shift_week, X)

    # Recommendations
    recs = _build_recommendations(ins_prob, dur_hrs, event_type,
                                   tz_shift, shift_week, strat_id)

    return {
        "prediction": {
            "sleep_duration_hrs":     round(dur_hrs, 2),
            "sleep_duration_label":   dur_label,
            "insomnia_probability":   round(ins_prob, 4),
            "insomnia_risk_level":    risk_level,
            "insomnia_risk_color":    risk_color,
            "recovery_days_predicted": round(rec_days, 1),
            "recovery_days_meaning":  _recovery_meaning(event_type, rec_days),
            "adaptation_strategy_id": strat_id,
            "adaptation_strategy":    strat,
        },
        "simulation": {
            "event_type":        ["none", "jet_lag", "night_shift"][event_type],
            "tz_shift_hrs":      tz_shift,
            "shift_week":        shift_week,
            "insomnia_risk_trajectory_7d": [round(v, 3) for v in traj],
            "trajectory_labels": [f"Day +{i+1}" for i in range(7)],
            "trajectory_peak":   round(max(traj), 3),
            "trajectory_trend":  "improving" if traj[-1] < traj[0] else "worsening",
        },
        "trends": {
            "avg_sleep_duration_hrs":   round(float(X[:, 0].mean()) * 12, 2),
            "avg_sleep_efficiency_pct": round(float(X[:, 1].mean()) * 100, 1),
            "avg_hrv_rmssd_ms":         round(float(X[:, 3].mean()) * 150, 1),
            "duration_7day":  [round(float(X[i, 0]) * 12, 2) for i in range(7)],
            "efficiency_7day": [round(float(X[i, 1]) * 100, 1) for i in range(7)],
            "hrv_7day":        [round(float(X[i, 3]) * 150, 1) for i in range(7)],
        },
        "context_notes":      context_notes,
        "insights":           insights,
        "recommendations":    recs,
        "clinical_disclaimer": CLINICAL_DISCLAIMER,
    }


# ── Helpers ──────────────────────────────────────────────────────────────────

def _recovery_meaning(event_type, rec_days):
    if event_type == 1:   # jet lag
        return (f"Model predicts ~{rec_days:.0f} days to restore normal "
                f"circadian alignment after timezone shift.")
    elif event_type == 2:  # night shift
        return (f"Model predicts ~{rec_days:.0f} days of significant circadian "
                f"misalignment impact at current shift pattern.")
    else:
        return "No active circadian disruption event detected."


def _build_context_notes(event_type, tz_shift, shift_week, ins_prob, rec_days, strat_id, age):
    notes = []
    if event_type == 1:
        direction = "eastward" if tz_shift > 0 else "westward"
        notes.append(
            f"Jet lag detected: {abs(tz_shift):.0f}h {direction} shift. "
            f"Eastward travel is harder for circadian adjustment (phase advance required)."
        )
        if tz_shift > 6:
            notes.append("Severe timezone shift (>6h) — expect 2–3 days of sleep fragmentation.")
        if age > 50:
            notes.append("Age >50: circadian recovery is slower. Allow extra time for adjustment.")
    elif event_type == 2:
        notes.append(
            f"Night shift worker detected (week {shift_week}). "
            f"Circadian misalignment builds progressively with shift duration."
        )
        if shift_week > 4:
            notes.append(
                "Extended night shift (>4 weeks): chronic misalignment risk. "
                "Rotating back to days should be gradual (1–2h/day max)."
            )
    if ins_prob > 0.5 and event_type > 0:
        notes.append(
            "Combined insomnia risk + circadian disruption detected. "
            "Prioritise the adaptation strategy immediately — don't wait for it to resolve."
        )
    return notes


def _build_insights(dur_hrs, ins_prob, rec_days, traj, event_type, tz_shift, shift_week, X):
    insights = []
    if event_type == 1:
        insights.append(
            f"Your circadian clock is adjusting to a {abs(tz_shift):.0f}h timezone shift. "
            f"ML model estimates {rec_days:.0f} days to full recovery."
        )
    elif event_type == 2:
        insights.append(
            f"Night shift week {shift_week}: your body clock is inversely aligned with the solar cycle. "
            f"Model predicts {rec_days:.0f} days of impact."
        )
    if max(traj) > 0.6:
        peak_day = traj.index(max(traj)) + 1
        insights.append(
            f"Insomnia risk trajectory peaks at Day +{peak_day} ({max(traj):.0%}). "
            f"Proactive intervention before this day is recommended."
        )
    if traj[-1] < traj[0] - 0.1:
        insights.append("7-day forecast shows improving insomnia risk trend — adaptation is working.")
    elif traj[-1] > traj[0] + 0.1:
        insights.append("7-day forecast shows worsening insomnia risk — intervention urgency is high.")
    if dur_hrs < 6.5:
        insights.append(f"Sleep duration ({dur_hrs:.1f}h) is below healthy threshold. "
                         "Circadian disruption events worsen sleep debt significantly.")
    hrv_avg = float(X[:, 3].mean()) * 150
    if hrv_avg < 30:
        insights.append(f"HRV is low ({hrv_avg:.0f} ms) — autonomic stress is elevated, "
                         "consistent with circadian misalignment.")
    if not insights:
        insights.append("No significant circadian disruption detected. Maintain current sleep routine.")
    return insights


def _build_recommendations(ins_prob, dur_hrs, event_type, tz_shift, shift_week, strat_id):
    recs = []

    # Strategy-specific first
    if strat_id == 1:
        recs.append({
            "title": "Morning Bright Light Therapy",
            "desc": (
                "Expose yourself to 10,000 lux bright light for 20–30 min immediately upon waking. "
                "This advances your circadian phase — most effective for westward jet lag and night shift recovery."
            )
        })
    elif strat_id == 2:
        recs.append({
            "title": "Melatonin + Gradual Phase Advance",
            "desc": (
                "Take 0.5–1mg melatonin 5–6 hours before your target bedtime. "
                "Advance bedtime by 15 min every 2 days. Most effective for eastward jet lag."
            )
        })
    elif strat_id == 3:
        recs.append({
            "title": "Sleep Restriction Therapy",
            "desc": (
                "Temporarily restrict time in bed to your actual sleep time (but not less than 5h). "
                "Builds sleep pressure, consolidates fragmented sleep. Extend by 15 min/week."
            )
        })
    elif strat_id == 4:
        recs.append({
            "title": "Gradual Shift Schedule Adaptation",
            "desc": (
                "If transitioning off night shifts, shift your sleep time 1–2 hours later per day "
                "toward the target schedule. Avoid abrupt changes — they worsen misalignment."
            )
        })

    # Event-specific
    if event_type == 1:
        recs.append({
            "title": "Pre-flight Circadian Pre-adjustment",
            "desc": (
                "3 days before eastward travel: advance bedtime/wake by 1h per day. "
                "For westward: delay bedtime by 1h per day. Reduces recovery by 40–60%."
            )
        })
    elif event_type == 2 and shift_week > 3:
        recs.append({
            "title": "Anchor Sleep Strategy",
            "desc": (
                "Keep a 4h 'anchor sleep' at the same time every day (even days off). "
                "This maintains a partial circadian rhythm signal and reduces health impact."
            )
        })

    # General
    if ins_prob > 0.5:
        recs.append({
            "title": "Cognitive Behavioural Therapy for Insomnia (CBT-I)",
            "desc": (
                "First-line evidence-based treatment. More effective than sleep medication long-term. "
                "Especially important when insomnia compounds circadian disruption."
            )
        })

    recs.append({
        "title": "Sleep Environment Optimisation",
        "desc": (
            "Dark (blackout blinds for day-sleepers), cool (16–19°C), quiet. "
            "For jet lag: match room darkness to destination night cycle immediately on arrival."
        )
    })

    return recs[:4]


# ── CLI demo ──────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("Running demo: Eastward jet lag (+8h timezone shift), Day 2")
    demo_days = []
    for i in range(7):
        demo_days.append({
            "sleep_duration_hrs":  4.5 + i * 0.15,
            "sleep_efficiency":    0.62,
            "heart_rate_resting":  74,
            "rmssd": 24, "sdnn": 28,
            "steps": 5000,
            "light_exposure_lux": 3000,
            "bedtime_hour":  7.0,           # sleeping during destination day
            "isi_score": 18, "phq_score": 8, "gad_score": 7, "meq_score": 48,
            "event_type":       1,          # jet lag
            "tz_shift_hrs":     8.0,        # eastward
            "shift_week":       0,
            "days_since_event": i,
            "chronotype_score": 0.45,
        })

    try:
        result = predict_from_questionnaire(demo_days, age=32, gender="male")
        print(json.dumps(result, indent=2))
    except FileNotFoundError as e:
        print(f"Note: {e}")
        print("Train the model first: python train_tcn_model.py")